name: Unit tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cd fen_cli && cargo build --verbose
    - name: Run cli tests
      run: cd fen_cli && cargo test --verbose
    - name: Run integration tests (swift client)
      run: cd integration-tests/client/SwiftClient && swift test
    - name: Run integration tests (rust server)
      run: cd integration-tests/server/rust_server && cargo test --verbose
